/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Cell: typeof import('./src/components/Cell.vue')['default']
    Contextmenu: typeof import('./src/components/Contextmenu.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    GridItem: typeof import('./src/components/Grid/GridItem.vue')['default']
    GridLayout: typeof import('./src/components/Grid/GridLayout.vue')['default']
    Group: typeof import('./src/components/Radio/group.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Image: typeof import('./src/components/Image/index.vue')['default']
    ImgBox: typeof import('./src/components/Wallpaper/components/ImgBox.vue')['default']
    Radio: typeof import('./src/components/Radio/index.vue')['default']
    Settings: typeof import('./src/components/Settings/index.vue')['default']
    Wallpaper: typeof import('./src/components/Wallpaper/index.vue')['default']
    WidgetList: typeof import('./src/components/WidgetList.vue')['default']
  }
}
